create table client (id bigint generated by default as identity, name varchar(255), address_id bigint, primary key (id));
create table address (id bigint generated by default as identity, street varchar(255), primary key (id));
create table phone (id bigint generated by default as identity, number varchar(255), client_id bigint not null, primary key (id));
alter table client add constraint FK_CLIENT_ADDRESS foreign key (address_id) references address (id);
alter table phone add constraint FK_PHONE_CLIENT foreign key (client_id) references client (id);


insert into address (street) values ('volodarskogo');
insert into address (street) values ('dzerzinskogo');
insert into address (street) values ('popova');
insert into address (street) values ('levitana');

insert into client (name,address_id ) values ('Jonny A Good', 1);
insert into client (name,address_id ) values ('Jonny B Good', 2);
insert into client (name,address_id ) values ('Jonny C Good', 4);

--
insert into phone (number, client_id) values ('666-55-55', 1);
insert into phone (number, client_id) values ('333-55-55', 1);
insert into phone (number, client_id) values ('111-55-55', 2);
insert into phone (number, client_id) values ('222-22-22', 2);
insert into phone (number, client_id) values ('111-11-11', 3);

