create table client (id bigint generated by default as identity, name varchar(255), address_id bigint, primary key (id));
create table address (id bigint generated by default as identity, street varchar(255), primary key (id));
create table phone (id bigint generated by default as identity, number varchar(255), client_id bigint not null, primary key (id));
alter table client add constraint FK_CLIENT_ADDRESS foreign key (address_id) references address (id);
alter table phone add constraint FK_PHONE_CLIENT foreign key (client_id) references client (id);