server:
  port: 8081

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5430/demodb
    username: usr
    password: pwd
  flyway:
    url: jdbc:postgresql://localhost:5430/demodb
    user: usr
    password: pwd


logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: TRACE

superRoom: 1408
